# Generated by Django 4.1.5 on 2023-01-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_favorite_owner_remove_favorite_product_and_more'),
        ('feedback', '0004_favourite'),
    ]

    operations = [
    ]
