# Generated by Django 4.1.5 on 2023-01-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Thrieler', 'Thrieler'), ('Mystery', 'Mystery'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Anti utopia', 'Anti utopia'), ('Utopia', 'Utopia')], max_length=50),
        ),
    ]
